server:
 port: 8081
 
spring:
 application:
  name: EUREKA-SERVER
  
eureka:
 instance:
  hostname: localhost
 client:
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka